### ISSUE TITLE
Reference to generic type 'Data' requires arguments in <...>

### ISSUE THREAD

**Issue by ruben44bac** [ServiceStack/ServiceStack.Swift#14]
Hi, I solved the first problem but I continue have this in **JsonServiceClient.swift**:

` LINE 73 : Reference to generic type 'Data' requires arguments in <...>`

and all the code that use `Data` have the same error

My **dtos** presents this problem:

```
Type '[String]' does not conform to protocol 'JsonSerializable'

Type 'Bool' does not conform to protocol 'JsonSerializable'

Type '[UsuarioGet]' does not conform to protocol 'JsonSerializable'

```

_Originally posted by @ruben44bac in https://github.com/ServiceStack/ServiceStack.Swift/issues/13#issuecomment-422370903_

**Comment by mythz** [comment]
Please note the error messages are not useful on their own, we [need to be able to repro the issue ourselves](https://github.com/ServiceStack/Issues).

Please create a small stand-alone project on GitHub we can run locally to generate the invalid Swift code.

Note: the generated Swift code for your App is available from the `/types/swift` route.

Also please post future issues to our issue tracker at https://github.com/ServiceStack/Issues
