### ISSUE TITLE
JsonServiceClient HTTP DELETE is misspelled

### ISSUE THREAD

**Issue by bramley-turner-stride** [ServiceStack/ServiceStack.Swift#3]
The HTTP verb DELETE is misspelled as DELTE in JsonServiceClient.HttpMethods. This results in such requests failing.

**Comment by Layoric** [comment]
When adding a new ServiceStack reference, the plugin should now pull down updated JsonServiceClient with fix.

**Comment by Layoric** [comment]
Confirmed Xcode 7.0/7.1 now pulling down updated JsonServiceClient. Thanks! :+1:
