### ISSUE TITLE
Wrong date format for GET requests

### ISSUE THREAD

**Issue by nowol** [ServiceStack/ServiceStack.Swift#4]
This is an issue similar to this [Java issue](https://github.com/ServiceStack/ServiceStack.Java/issues/10).  Date values are not serialized correctly when they are used in the URL.  Other data types (e.g.: TimeSpan) may be affected as well.

```
/json/reply/MyGetRequest?date=2015-11-11 14:42:03
```

This is the local date instead of the UTC date so when ServiceStack 'reads', it converts it to UTC which could cause issue if the client and the server are not in the same timezone.  For testing purposes, I changed the verb to POST and this was the date format in the body of the request: 2015-11-11T19:45:54.092Z

```
    public class MyGetRequest : IReturn<Token>
    {
        public DateTime Date { get; set; }
    }
```

**Comment by nowol** [comment]
Can you do a similar fix that was used for this [Java issue](https://github.com/ServiceStack/ServiceStack.Java/issues/10)?

I tried fixing the issue myself (see below) but I'm sure you'll find a better solution since I have only been working in Swift for 2 weeks.

```
    public func createUrl<T : JsonSerializable>(dto:T, query:[String:String] = [:]) -> String {
        var requestUrl = self.replyUrl + T.typeName

        var sb = ""
        for pi in T.properties {
            if var strValue = pi.jsonValueAny(dto) {
                sb += sb.length == 0 ? "?" : "&"

                if (strValue[0] == "\"" && strValue[strValue.length - 1] == "\"")
                {
                    strValue = strValue[strValue.startIndex.advancedBy(1)..<strValue.endIndex.advancedBy(-1)];
                }

                sb += "\(pi.name.urlEncode()!)=\(strValue.urlEncode()!)"
            }
            else if var strValue = pi.stringValueAny(dto) {
                sb += sb.length == 0 ? "?" : "&"
                sb += "\(pi.name.urlEncode()!)=\(strValue.urlEncode()!)"
            }
        }

        for (key,value) in query {
            sb += sb.length == 0 ? "?" : "&"
            sb += "\(key)=\(value.urlEncode()!)"
        }

        requestUrl += sb

        return requestUrl
    }
```

**Comment by mythz** [comment]
FYI, the queryString is now serializing values as JSON in this commit: https://github.com/ServiceStack/ServiceStack.Swift/commit/00821a21f6e1ea41251c055b45b51fe31b29a6b3

I've also changed it to serialize WCF JSON format to retain the [same behavior as the Java ServiceClient](https://github.com/ServiceStack/ServiceStack.Java/blob/a2537aedfa9d7179331df4c8d0111fa5046875af/src/AndroidClient/client/src/test/java/net/servicestack/client/tests/JsonTests.java#L54)
