### ISSUE TITLE
Unable to deserialize array of objects

### ISSUE THREAD

**Issue by nowol** [ServiceStack/ServiceStack.Swift#5]
I'm having an [issue](https://forums.servicestack.net/t/servicestack-swift-support-for-array-response/1642) deserializing a request that return a list of object (e.g.: `IReturn<SomeClass>`).  I know that this is not supported and that @mythz do not want to automatically generate wrappers to fix this issue (he has good arguments in the thread).

Therefore I am proposing adding an extension point to the `Swift client` where the developers will be able to handle the deserialization themselves if the normal deserialization was not able to handle the returned object.  For this to work, ServiceStack.Swift would need to provide a new protocol (`CanPopulateFromJsonObject`) and developers could implement this protocol to handle their needs.

Let me know what you think.

**Protocol:**

```
protocol CanPopulateFromJsonObject // feel free to change the name
{
    func fromJsonObject(any: AnyObject?) -> Bool
}
```

**_Changes to fromJson:**_

```
        static func fromJson<T : JsonSerializable>(instance:T, json:String) -> T? {
        if instance is NSString || instance is String {
            if let value = json as? T {
                return value
            }
        }

        let jsonObject = parseJson(json)
        if (jsonObject != nil) {
            if let map = jsonObject as? NSDictionary {
                return populate(instance, map: map, propertiesMap: T.propertyMap)
            }

            if let populator = instance as? CanPopulateFromJsonObject {
                if (populator.fromJsonObject(jsonObject)) {
                    return instance
                }
            }
        }

        return nil
    }
```

**_Sample usage:**_
This has do be done by the developer for each class that he wants to support.

```

public class ArrayOfSomeClass : CanPopulateFromJsonObject, JsonSerializable
{
    public required init() {}
    public static var typeName:String { return "ArrayOfSomeClass" }
    public static var metadata = Metadata.create([])
    public var values = [SomeClass]()

    public func fromArray(array:NSArray)
    {
        for(item) in array {
            if let obj = SomeClass.fromObject(item) {
                values.append(obj)
            }
        }
    }
    public func fromJsonObject(any: AnyObject?) -> Bool {
        if let array = any as? NSArray {
            fromArray(array)
            return true
        }
        return false
    }

    // I didn't implement these methods for this sample
    public static func fromObject(any:AnyObject) -> ArrayOfSomeClass? { return nil }
    public func toJson() -> String { return "" }
    public func toString() -> String { return toJson() }
    public static func fromString(string:String) -> ArrayOfSomeClass? { return nil }
}

public class SomeClass
{
    public required init() {}
    var someValue: String?
}

extension SomeClass : JsonSerializable
{
    public static var typeName:String { return "SomeClass" }
    public static var metadata = Metadata.create([
        Type<SomeClass>.optionalProperty("someValue", get: { $0.someValue }, set: { $0.someValue = $1 }),
        ])

    public typealias T = SomeClass
    public static func fromObject(any:AnyObject) -> SomeClass? {
        if let map = any as? NSDictionary {
            return populate(SomeClass(), map: map, propertiesMap: SomeClass.propertyMap)
        }
        return nil
    }
}

public class MyRequest : IReturn
{
    public typealias Return = ArrayOfSomeClass
    required public init(){}
}

// Testing
var jsonString = "[{ \"someValue\": \"a\"}, { \"someValue\": \"b\"}]"
var obj = Type<ArrayOfSomeClass>.fromString(ArrayOfSomeClass(), string: jsonString)

print("items:")
for(item) in obj!.values {
    print(item.someValue)
}

```

**Comment by nowol** [comment]
I should mention that for this to work I had to configure my host with this option:

```
SwiftGenerator.IgnoreArrayReturnTypes = false;
```

**Comment by nowol** [comment]
I played a bit more with the above code and I changed the `fromJson` to this:

```
    static func fromJson<T : JsonSerializable>(instance:T, json:String) -> T? {
        if instance is NSString || instance is String {
            if let value = json as? T {
                return value
            }
        }

        let jsonObject = parseJson(json)
        if (jsonObject != nil) {
            var wasDeserialized = false
            var deserializedInstance = instance
            if let map = jsonObject as? NSDictionary {
                deserializedInstance = populate(instance, map: map, propertiesMap: T.propertyMap)
                wasDeserialized = true
            }
            // allow the developers to extend the deserialization process
            if let populator = deserializedInstance as? CanPopulateFromJsonObject {
                if (populator.fromJsonObject(jsonObject)) {
                    wasDeserialized = true
                }
            }
            if (wasDeserialized) {
                 return deserializedInstance
            }
        }
        return nil
    }
```

As you can see from the change, instead of completely overriding the deserialization process the code now tries to populate the instance as before and allows the developer to specify a custom deserialization process.  This new `fromJson` function can solve 2 of my issues:
- Allowing me to handle IReturn<int[]> (array or list) myself without customizing the JsonClient's code myself
- Allowing me to handle problematic classes that contains a property with an object datatype (bad idea I know but I cannot change this) without redeclaring the whole class.  I could extend the class to add the 'object' property and deserialize it myself.

I still have to find a better way to handle the `wasDeserialized` variable but it should give you an idea of what I am trying to achieve.

**Comment by nowol** [comment]
Additionally, we could extend this code to the toJson method to allow developers to serialized properties that cannot be serialized by ServiceStack.

**Comment by mythz** [comment]
How did you get `SwiftGenerator.IgnoreArrayReturnTypes = false;` to not have a build error?

For this C# DTO:

``` csharp
public class HelloList : IReturn<List<ListResult>>
{
    public List<string> Names { get; set; }
}
```

It generates this in Swift:

``` swift
public class HelloList : IReturn
{
    public typealias Return = [ListResult]

    required public init(){}
    public var names:[String] = []
}

extension HelloList : JsonSerializable {
    public static var typeName:String { return "HelloList" }
    public static var metadata = Metadata.create([
            Type<HelloList>.arrayProperty("names", get: { $0.names }, set: { $0.names = $1 })
        ])
}
```

Which results in a build error because `[ListResult]` doesn't implement `JsonSerializable` and trying to implement `JsonSerializable` on a generic array is seg faulting the compiler.

**Comment by nowol** [comment]
I forgot to mention that I have a "response filter" (see below) that takes the output of the requests and does the following steps:
- extract the return array types (`[ListResult]`)
- generate a wrapper class that implements my CanPopulateFromJsonObject protocol
- change the return types to the wrapper types
- add the generated wrappers to the end of the request

---

The project I am working on does a few things that are not best practice (as you may have guessed from all my messages) : returning list/array, value types, inheritance in requests/response object, etc. To workaround these design issues, I create a `MySwiftTypeGeneratorRequest` and I am modifying the metadata to 'flatten' the class inheritance before calling the SwiftGenerator.  It is a low level operation and I expect to maintain this myself in the future as ServiceStack's code changes.

**Comment by mythz** [comment]
This is all too hacky, you'll need to maintain a custom version with the behavior you want. I expect Swift will fix their segfaults + generic type extension limitations in future and I'll re-enable Array extensions when they do.
