### ISSUE TITLE
Exception when response is nil

### ISSUE THREAD

**Issue by bull-xu** [ServiceStack/ServiceStack.Swift#7]
When the response is nil, line 267 `throw e` and then line 277 `catch var ex as NSError` but the response is nil now, so the line 278 self.handleResponse in catch block will crash the app on `response!`:

> fatal error: unexpectedly found nil while unwrapping an Optional value

![image](https://cloud.githubusercontent.com/assets/12520500/16705455/bbec69de-45cd-11e6-8984-3b2216809a49.png)

**Comment by mythz** [comment]
Can you provide the DTO Request/Response class definition you used?

**Comment by bull-xu** [comment]
I called the CancelRequest for a previous request. Will provide more details while the error hits again. Cheers.

**Comment by mythz** [comment]
Hi I've added checks to handle when response is nil in this commit: https://github.com/ServiceStack/ServiceStack.Swift/commit/b612900a8c5499875ced5d5c1f5091429843e62f

Next time you add a new ServiceStack reference you should pull down the latest version with this fix. 

If you still have issues please reopen with a repro, thx.
